# Generated by Django 5.1.1 on 2024-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Ford', 'Ford'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Toyota', 'Toyota'), ('Mercedes', 'Mercedes'), ('Volkswagen', 'Volkswagen'), ('Honda', 'Honda'), ('Chevrolet', 'Chevrolet'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('Kia', 'Kia'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Volvo', 'Volvo'), ('Tesla', 'Tesla'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('Subaru', 'Subaru'), ('Jaguar', 'Jaguar'), ('Ferrari', 'Ferrari'), ('Porsche', 'Porsche'), ('Lamborghini', 'Lamborghini'), ('Land Rover', 'Land Rover')], max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('Car', 'Car'), ('Van', 'Van'), ('Scooter', 'Scooter')], max_length=10)),
                ('plate_number', models.CharField(max_length=15, unique=True)),
                ('seats', models.PositiveIntegerField()),
                ('transmission_type', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(choices=[('Barcelona', 'Barcelona'), ('Madrid', 'Madrid'), ('Valencia', 'Valencia')], max_length=50)),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('mileage', models.PositiveIntegerField()),
                ('doors', models.PositiveIntegerField()),
                ('storage', models.PositiveBigIntegerField()),
                ('air_conditioning', models.BooleanField(default=True)),
                ('gps', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('parking_sensors', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
