# Generated by Django 5.1.1 on 2024-10-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
    ]
