# Generated by Django 5.1.1 on 2024-10-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_car_bluetooth_remove_car_parking_sensors'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='air_conditioning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='bluetooth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='gps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='parking_sensors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='storage',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Car', 'Car'), ('Van', 'Van'), ('Scooter', 'Scooter')], default='Car', max_length=10),
        ),
    ]
